import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BookOpen, Bot, CheckCircle2, FileUp, GraduationCap, Plus, ScanLine, Sparkles, Users } from 'lucide-react';
import { supabase, supabaseEnabled } from './supabase';
import './styles.css';

const seed = [
  {id:1,title:'Đại số cơ bản — Phương trình bậc nhất',subject:'Toán học',due:'20/06/2025',questions:5,participants:28,status:'Đang mở'},
  {id:2,title:'Đọc hiểu: Mùa xuân nho nhỏ',subject:'Ngữ văn',due:'18/06/2025',questions:6,participants:24,status:'Đang mở'},
  {id:3,title:'Từ vựng Unit 8',subject:'Tiếng Anh',due:'12/06/2025',questions:10,participants:31,status:'Đã đóng',score:8.5}
];
function App(){
 const [role,setRole]=useState('student'),[page,setPage]=useState('home'),[items,setItems]=useState(seed),[active,setActive]=useState(null),[showCreate,setShowCreate]=useState(false),[showAuth,setShowAuth]=useState(false),[session,setSession]=useState(null),[toast,setToast]=useState('');
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setSession(data.session));const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 const notify=m=>{setToast(m);setTimeout(()=>setToast(''),2600)};
 const add=a=>{setItems([{...a,id:Date.now(),participants:0,status:'Đang mở'},...items]);setShowCreate(false);setPage('assignments');notify('Đề bài đã được xuất bản.');};
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark"><GraduationCap/></span><span>Lớp học số</span></div><div className="identity-card"><div className="avatar">{role==='student'?'AN':'MT'}</div><div><b>{session?.user?.email|| (role==='student'?'An Nguyễn':'Minh Trần')}</b><small>{supabaseEnabled?'Đã kết nối Supabase':role==='student'?'Học sinh lớp 9A1':'Gia sư Toán & Văn'}</small></div></div><nav><Nav label="Tổng quan" onClick={()=>setPage('home')} active={page==='home'}/><Nav label={role==='student'?'Bài tập của tôi':'Quản lý đề bài'} onClick={()=>setPage('assignments')} active={page==='assignments'}/><Nav label="Lớp học" onClick={()=>setPage('classes')} active={page==='classes'}/>{role==='tutor'&&<Nav label="Tạo đề bằng AI" onClick={()=>setPage('scan')} active={page==='scan'}/>}</nav><div className="sidebar-bottom"><button className="role-switch" onClick={()=>{setRole(role==='student'?'tutor':'student');setPage('home')}}><Users size={17}/>Đổi sang {role==='student'?'Gia sư':'Học sinh'}</button></div></aside><main><header><div><p className="eyebrow">{role==='student'?'KHÔNG GIAN HỌC TẬP':'KHÔNG GIAN GIẢNG DẠY'}</p><h1>{page==='home'?`Chào ${role==='student'?'An':'cô Minh'} 👋`:page==='scan'?'Tạo đề từ ảnh bằng AI':page==='classes'?'Lớp học của bạn':role==='student'?'Bài tập của tôi':'Quản lý đề bài'}</h1></div><div className="header-actions">{role==='tutor'&&<button className="primary" onClick={()=>setShowCreate(true)}><Plus size={17}/>Tạo đề mới</button>}{supabaseEnabled&&!session&&<button className="outline" onClick={()=>setShowAuth(true)}>Đăng nhập</button>}<div className="header-avatar">{session?.user?.email?.slice(0,2).toUpperCase()||'AN'}</div></div></header><div className="content">{page==='home'&&<Home role={role} items={items} open={setActive} create={()=>setShowCreate(true)}/>} {page==='assignments'&&<Assignments role={role} items={items} open={setActive} create={()=>setShowCreate(true)}/>} {page==='classes'&&<Classes/>}{page==='scan'&&<Scan onCreate={add}/>}</div></main>{active&&<Work assignment={active} role={role} close={()=>setActive(null)}/>} {showCreate&&<Create close={()=>setShowCreate(false)} create={add}/>} {showAuth&&<Auth close={()=>setShowAuth(false)} done={()=>{setShowAuth(false);notify('Đăng nhập thành công.')}}/>}{toast&&<div className="toast"><CheckCircle2 size={18}/>{toast}</div>}</div>
}
const Nav=({label,onClick,active})=><button className={'nav-item '+(active?'active':'')} onClick={onClick}><BookOpen size={18}/><span>{label}</span></button>;
function Home({role,items,open,create}){return <><section className="hero"><div><span className="pill"><Sparkles size={14}/>Học thông minh mỗi ngày</span><h2>{role==='student'?'Sẵn sàng chinh phục\nmột ngày mới?':'Tạo bài tập hiệu quả,\ntheo dõi tiến bộ dễ dàng.'}</h2><p>{role==='student'?'Bạn còn 3 bài tập chưa hoàn thành. Hãy bắt đầu ngay.':'Đăng đề từ tệp có sẵn hoặc quét ảnh để AI giúp tạo câu hỏi.'}</p><button className="light-button" onClick={role==='student'?()=>open(items[0]):create}>{role==='student'?'Làm bài ngay':'Tạo đề mới'}</button></div><div className="hero-art"><div className="book-icon"><BookOpen size={65}/></div></div></section><section className="stat-grid">{(role==='student'?[['03','Bài đang chờ'],['08','Điểm trung bình'],['12','Bài đã nộp']]:[['03','Đề đang mở'],['12','Bài cần chấm'],['8.4','Điểm trung bình']]).map(x=><article className="stat" key={x[1]}><strong>{x[0]}</strong><div><b>{x[1]}</b><small>Cập nhật hôm nay</small></div></article>)}</section><section className="section-head"><div><h2>{role==='student'?'Việc cần làm':'Đề bài gần đây'}</h2><p>Ưu tiên hoàn thành trước hạn.</p></div></section><List role={role} items={items.slice(0,3)} open={open}/></>}
function Assignments({role,items,open,create}){return <><div className="page-intro"><p>Chọn bài tập để làm, chấm điểm hoặc theo dõi tiến độ.</p>{role==='tutor'&&<button className="primary" onClick={create}><Plus size={17}/>Tạo đề bài</button>}</div><List role={role} items={items} open={open}/></>}
function List({role,items,open}){return <div className="assignment-list">{items.map(a=><article className="assignment" key={a.id}><div className="subject-icon math"><BookOpen size={20}/></div><div className="assignment-main"><div className="assignment-title"><h3>{a.title}</h3><span className={'status '+(a.status==='Đang mở'?'open':'closed')}>{a.status}</span></div><p>{a.subject} · {a.questions} câu hỏi · Hạn nộp: <b>{a.due}</b></p></div><div className="assignment-meta">{role==='student'&&a.score?<b className="score">{a.score}/10</b>:<button className="outline" onClick={()=>open(a)}>{role==='student'?'Làm bài':'Xem bài'}</button>}</div></article>)}</div>}
function Classes(){return <div className="class-grid">{['Toán 9 — Nâng cao','Ngữ văn 9 — Chuyên đề','Tiếng Anh 9 — B1'].map(c=><article className="class-card" key={c}><div className="class-top">A</div><h3>{c}</h3><p>Gia sư Minh Trần</p><button className="link-btn">Truy cập lớp</button></article>)}</div>}
function Create({close,create}){const [v,setV]=useState({title:'',subject:'Toán học',due:'',file:''});return <div className="overlay"><div className="modal create"><button className="close" onClick={close}>×</button><span className="modal-kicker">GIA SƯ</span><h2>Tạo đề bài mới</h2><p>Đính kèm tệp nguồn hoặc dùng AI quét ảnh ở menu bên trái.</p><label>Tiêu đề<input value={v.title} onChange={e=>setV({...v,title:e.target.value})}/></label><div className="form-row"><label>Môn học<select value={v.subject} onChange={e=>setV({...v,subject:e.target.value})}><option>Toán học</option><option>Ngữ văn</option><option>Tiếng Anh</option></select></label><label>Hạn nộp<input type="date" value={v.due} onChange={e=>setV({...v,due:e.target.value})}/></label></div><label className="upload-field"><FileUp size={21}/><span>{v.file||'Đính kèm PDF, DOCX hoặc ảnh nguồn'}</span><input type="file" onChange={e=>setV({...v,file:e.target.files?.[0]?.name||''})}/></label><button className="primary full" disabled={!v.title} onClick={()=>create({...v,due:v.due||'Chưa đặt hạn',questions:[]})}>Xuất bản đề bài</button></div></div>}
function Scan({onCreate}){const [file,setFile]=useState(null),[loading,setLoading]=useState(false),[quiz,setQuiz]=useState(null),[error,setError]=useState('');const scan=async()=>{setLoading(true);setError('');const f=new FormData();f.append('image',file);f.append('title',`Đề AI — ${file.name}`);try{const r=await fetch('/api/scan-to-quiz',{method:'POST',body:f});const d=await r.json();if(!r.ok)throw Error(d.message);setQuiz(d)}catch(e){setError(e.message)}finally{setLoading(false)}};return <div className="scan-layout"><section className="scan-card"><div className="ai-badge"><Bot/></div><h2>Biến ảnh thành đề bài</h2><p>OpenAI Vision sẽ đọc ảnh và tạo câu hỏi để gia sư duyệt.</p><label className="scan-upload"><ScanLine size={38}/><b>{file?file.name:'Chọn ảnh đề bài'}</b><small>PNG, JPG · tối đa 10 MB</small><input type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0])}/></label><button className="primary" disabled={!file||loading} onClick={scan}>{loading?'Đang quét...':'Quét ảnh với AI'}<Sparkles size={16}/></button>{error&&<p style={{color:'#ba4945'}}>{error}</p>}</section>{quiz&&<section className="quiz-preview"><span className="modal-kicker">{quiz.demo?'BẢN DEMO':'BẢN NHÁP AI'}</span><h2>{quiz.title}</h2>{quiz.questions.map(q=><div className="ai-question" key={q.id}><b>Câu {q.id} · {q.points} điểm</b><p>{q.text}</p>{q.options&&<div className="options">{q.options.map((o,i)=><span key={o}>{'ABCD'[i]}. {o}</span>)}</div>}</div>)}<button className="primary full" onClick={()=>onCreate({...quiz,subject:'Từ ảnh quét',due:'Chưa đặt hạn'})}>Duyệt & xuất bản đề</button></section>}</div>}
function Work({assignment,role,close}){const [answers,setAnswers]=useState({}),[done,setDone]=useState(false);return <div className="overlay"><div className="modal assignment-modal"><button className="close" onClick={close}>×</button><span className="modal-kicker">{assignment.subject}</span><h2>{assignment.title}</h2>{role==='tutor'?<div className="tutor-summary"><strong>{assignment.participants||0}<small>học sinh tham gia</small></strong><strong>8.4<small>điểm trung bình</small></strong></div>:done?<div className="result"><CheckCircle2 size={48}/><h3>Bạn đã nộp bài!</h3><strong>{Math.round(Object.keys(answers).length/3*10*10)/10}/10</strong><button className="primary" onClick={close}>Hoàn tất</button></div>:<div className="question-form">{['Giải phương trình: 2x + 4 = 16','Chọn đáp án phù hợp','Trình bày cách giải'].map((q,i)=><label key={q}><b>Câu {i+1}. {q}</b><textarea value={answers[i]||''} onChange={e=>setAnswers({...answers,[i]:e.target.value})}/></label>)}<button className="primary full" onClick={()=>setDone(true)}>Nộp bài & chấm điểm</button></div>}</div></div>}
function Auth({close,done}){const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[mode,setMode]=useState('login'),[error,setError]=useState('');const submit=async()=>{const r=mode==='login'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});if(r.error)setError(r.error.message);else done()};return <div className="overlay"><div className="modal create"><button className="close" onClick={close}>×</button><h2>{mode==='login'?'Đăng nhập':'Đăng ký'}</h2><label>Email<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Mật khẩu<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p style={{color:'#b54b44'}}>{error}</p>}<button className="primary full" onClick={submit}>{mode==='login'?'Đăng nhập':'Đăng ký'}</button><button className="link-btn" onClick={()=>setMode(mode==='login'?'signup':'login')}>{mode==='login'?'Tạo tài khoản':'Đã có tài khoản?'}</button></div></div>}
createRoot(document.getElementById('root')).render(<App/>);
